/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorEstaciona;
import funcionpanel.EscuchaBDPlaza;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.ModeloEstaciona;

/**
 *
 * @author Danilo Martinez
 */
public class AdminPortal extends javax.swing.JFrame {
    public static String rut;
    public AdminPortal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpVentana = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmnInicioS = new javax.swing.JMenuItem();
        jmnPass = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmnVerEdit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmnAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estacionamiento INACAP");

        jdpVentana.setBackground(new java.awt.Color(204, 204, 204));
        jdpVentana.setName(""); // NOI18N

        javax.swing.GroupLayout jdpVentanaLayout = new javax.swing.GroupLayout(jdpVentana);
        jdpVentana.setLayout(jdpVentanaLayout);
        jdpVentanaLayout.setHorizontalGroup(
            jdpVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        jdpVentanaLayout.setVerticalGroup(
            jdpVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jmnInicioS.setText("Inicio sesion");
        jmnInicioS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnInicioSActionPerformed(evt);
            }
        });
        jMenu1.add(jmnInicioS);

        jmnPass.setText("Cambiar contraseña");
        jmnPass.setEnabled(false);
        jmnPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnPassActionPerformed(evt);
            }
        });
        jMenu1.add(jmnPass);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Administrador");

        jmnVerEdit.setText("Ver/Editar usuarios");
        jmnVerEdit.setEnabled(false);
        jmnVerEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnVerEditActionPerformed(evt);
            }
        });
        jMenu3.add(jmnVerEdit);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayuda");

        jMenuItem5.setText("Probar conexion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jmnAcerca.setText("Acerca de");
        jmnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAcercaActionPerformed(evt);
            }
        });
        jMenu2.add(jmnAcerca);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpVentana)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpVentana)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnInicioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnInicioSActionPerformed
        InicioSesion iSesion = new InicioSesion();
        jdpVentana.add(iSesion);
        iSesion.show();
    }//GEN-LAST:event_jmnInicioSActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        boolean i;
        ControladorEstaciona ce = new ControladorEstaciona();
        i = ce.verificarConexionBD();
        if(i)
        {
            JOptionPane.showMessageDialog(null, "La conexion esta establecida!","Probar conexion",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error en la conexion, contacte al administrador","Probar conexion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnPassActionPerformed
        CambioPass camP = new CambioPass();
        jdpVentana.add(camP);
        camP.show();
    }//GEN-LAST:event_jmnPassActionPerformed

    private void jmnVerEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnVerEditActionPerformed
        try
        {
            VerEditarUsuarios veu = new VerEditarUsuarios();
            jdpVentana.add(veu);
            veu.setMaximum(true);
            veu.show();
        }
        catch (PropertyVetoException ex)
        {
            
        }
    }//GEN-LAST:event_jmnVerEditActionPerformed

    private void jmnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAcercaActionPerformed
        AcercaDe acd = new AcercaDe();
        jdpVentana.add(acd);
        Dimension desktopSize = jdpVentana.getSize();
        Dimension FrameSize = acd.getSize();
        acd.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        acd.show();
    }//GEN-LAST:event_jmnAcercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    public static javax.swing.JDesktopPane jdpVentana;
    private javax.swing.JMenuItem jmnAcerca;
    public static javax.swing.JMenuItem jmnInicioS;
    public static javax.swing.JMenuItem jmnPass;
    public static javax.swing.JMenuItem jmnVerEdit;
    // End of variables declaration//GEN-END:variables
}
