/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorEstaciona;
import funcionpanel.EscuchaBDPlaza;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.ModeloEstaciona;

/**
 *
 * @author Danilo Martinez
 */
public class InicioSesion extends javax.swing.JInternalFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    public void iniciosesion()
    {
        String user, pass, rol;
        ControladorEstaciona ce = new ControladorEstaciona();
        user = txtRut.getText();
        pass = String.valueOf(txtPassw.getPassword());
        try
        {
            if(user.length() > 0 && pass.length() > 0)
            {
                rol = ce.login(user, pass);
                if((!rol.equals("0")) && (!rol.equals("-1")))
                {
                    DiagramaEstaciona diag = new DiagramaEstaciona();
                    if(rol.equals("administrador"))
                    {
                        AdminPortal.jmnVerEdit.setEnabled(true);
                        AdminPortal.jdpVentana.add(diag);
                        diag.setMaximum(true);
                        diag.show();
                        this.dispose();
                    }
                    else
                    {
                        AdminPortal.jdpVentana.add(diag);
                        diag.setMaximum(true);
                        diag.show();
                        this.dispose();
                    }
                    AdminPortal.jmnInicioS.setEnabled(false);
                    AdminPortal.jmnPass.setEnabled(true); 
                } 
                else
                {
                    if(rol.equals("0"))
                    {
                        JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos","Validacion",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "No hay conexion con el servidor, contacta a un administrador","Validacion",JOptionPane.ERROR_MESSAGE);
                    }
                    txtRut.setText("");
                    txtPassw.setText("");
                    txtRut.requestFocus();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Ingrese los campos solicitados","Validacion",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (PropertyVetoException ex)
        {
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRut = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtRut = new javax.swing.JTextField();
        lblPassw = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAcceder = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtPassw = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Inicio sesion");

        lblRut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRut.setText("RUT:");

        lblInicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("INICIO SESION PLATAFORMA");
        lblInicio.setToolTipText("");

        txtRut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRutKeyPressed(evt);
            }
        });

        lblPassw.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPassw.setText("Contraseña");

        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        txtPassw.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPassw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswActionPerformed(evt);
            }
        });
        txtPassw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassw)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnAcceder)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPassw, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblInicio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRut)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassw)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcceder)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        iniciosesion();
    }//GEN-LAST:event_btnAccederActionPerformed

    private void txtPasswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            iniciosesion();
        }   
    }//GEN-LAST:event_txtPasswKeyPressed

    private void txtPasswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswActionPerformed

    private void txtRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            iniciosesion();
        }
    }//GEN-LAST:event_txtRutKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPassw;
    private javax.swing.JLabel lblRut;
    private javax.swing.JPasswordField txtPassw;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
